name: Workflow for Codecov Action
on: [pull_request]

permissions: {}

jobs:
  run:
    permissions:
      id-token: write
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ${{ github.actor == 'dependabot[bot]' && fromJSON('["ubuntu-latest"]') || fromJSON('["macos-latest", "windows-latest", "ubuntu-latest", "ubuntu-24.04-arm"]') }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Upload test results to Codecov (calculator)
        uses: ./
        with:
          dry_run: true
          fail_ci_if_error: true
          files: ./demo/calculator/junit.xml,
          flags: ${{ matrix.os }}
          verbose: true
          token: dummy-token
      - name: Upload test results to Codecov (calculator) (oidc)
        uses: ./
        with:
          dry_run: true
          use_oidc: true
          fail_ci_if_error: true
          files: ./demo/calculator/junit.xml
          flags: ${{ matrix.os }}
          verbose: true
      - name: Upload test results to Codecov (demo)
        uses: ./
        with:
          dry_run: true
          fail_ci_if_error: true
          files: ./demo/coverage-test/junit.xml
          flags: ${{ matrix.os }}
          verbose: true
          token: dummy-token
      - name: Upload test results to Codecov (calculator) (staging)
        uses: ./
        with:
          dry_run: true
          fail_ci_if_error: true
          files: ./demo/calculator/junit.xml
          flags: ${{ matrix.os }}
          verbose: true
          url: dummy-staging-url
          token: dummy-token-staging
      - name: Upload test results to Codecov (demo) (staging)
        uses: ./
        with:
          dry_run: true
          fail_ci_if_error: true
          url: dummy-staging-url
          token: dummy-token-staging
          files: ./demo/coverage-test/junit.xml
          flags: ${{ matrix.os }}
          verbose: true
